---
functional:
- Пользователь должен иметь возможность искать товары по ключевому слову или категории
- Пользователь должен иметь возможность фильтровать товары
- Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
- Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
- Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
- Сайт должен быть безопасным и защищать данные пользователя
- Сайт должен иметь мобильную версию
- Сайт нужно протестировать на совместимость с последними версиями браузеров
- Сайт должен быть доступен на различных устройствах
- Важно, чтобы сайт мог обрабатывать большое количество трафика
implicit:
- Пользователь должен иметь возможность указать количество при добавлении товара в корзину
- Пользователь должен иметь возможность изменить количество конкретного товара в корзине
- Пользователь должен иметь возможность сохранить информацию о добавленных в корзину товарах
- Пользователь должен иметь возможность проверить информацию о товарах в форме заказа
- Результаты поиска товаров по ключевому слову должны быть одинаковыми независимо от регистра символов
- Пользователь должен иметь возможность удалить товары из корзины
- Для товара должны быть указаны - название, цена, количество в наличии, описание
- Поле поиска по ключевому слову должно игнорировать